# Generated by Django 4.2.11 on 2026-01-29 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_title', models.CharField(help_text='The name of the event', max_length=200)),
                ('event_date', models.DateField(help_text='The date of the event')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The event this gift list is for', on_delete=django.db.models.deletion.RESTRICT, to='xmas_lists.event')),
                ('user', models.ForeignKey(help_text='The user this list is for', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The title of this giftlist item', max_length=200)),
                ('url', models.URLField(blank=True, help_text='The URL where this item can be purchased', null=True, verbose_name='URL')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='How much this item costs', max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='USD', help_text="The currency refered to by 'price'", max_length=3, null=True)),
                ('priority', models.CharField(choices=[('1', 'Very Low'), ('2', 'Low'), ('3', 'Medium'), ('4', 'High'), ('5', 'Very High')], default='3', help_text='The comparative desirability of the item', max_length=1)),
                ('list', models.ForeignKey(help_text='The list this item is in', on_delete=django.db.models.deletion.CASCADE, to='xmas_lists.list')),
            ],
        ),
        migrations.CreateModel(
            name='ListItemPurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_comments', models.CharField(max_length=1000)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='xmas_lists.listitem', unique=True)),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='list',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_user_pair'),
        ),
    ]
