# Generated by Django 6.0.1 on 2026-01-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listitem',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
