# Generated by Django 4.2.11 on 2026-01-29 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='listitempurchased',
            options={'verbose_name': 'List Item Purchased', 'verbose_name_plural': 'List Items Purchased'},
        ),
        migrations.AlterField(
            model_name='listitem',
            name='url',
            field=models.URLField(blank=True, help_text='The URL where this item can be purchased', max_length=1000, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='listitempurchased',
            name='list_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='xmas_lists.listitem'),
        ),
    ]
