# Generated by Django 4.2.11 on 2026-01-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_lists', '0002_alter_list_options_alter_listitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['-priority', 'price']},
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.UniqueConstraint(fields=('title', 'list'), name='unique_title_list_pair'),
        ),
    ]
