# Generated by Django 6.0.1 on 2026-02-04 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_lists', '0003_alter_listitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['created_at'], 'permissions': (('edit_list', 'Edit List'),)},
        ),
    ]
