# Generated by Django 6.0.1 on 2026-02-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_lists', '0004_alter_list_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['created_at']},
        ),
    ]
