# Generated by Django 6.0.1 on 2026-02-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_lists', '0007_eventinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvite',
            name='accepted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
