# Generated by Django 6.0.1 on 2026-02-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmas_lists', '0008_alter_eventinvite_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvite',
            name='rejected_at',
            field=models.DateTimeField(null=True),
        ),
    ]
